trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  displayName: Get secrets from keyvault
  inputs:
    azureSubscription: 'RG-VaibhavUniyal-POC-0024'
    KeyVaultName: 'kv-rgvaibhavpoc-test001'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: CmdLine@2
  displayName: Write secrets into a file
  inputs:
    script: |
      echo $(dummy-secret)
      echo $(dummy-secret) > secret.txt
      cat secrets.txt

- task: CopyFiles@2
  displayName: Copy Secrets Files
  inputs:
    Contents: secrets.txt
    targetFolder: '$(Build.ArtifactStagingDirectory)' 
    
- task: PublishBuildArtifacts@1
  displayName: Publish Secrets Files
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: drop
    publishLocation: 'Container'
